apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - image: authapp
        name: django
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: jwtAuth.settings
        - name: DATABASE_NAME
          value: authdb
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 8000
     targetPort: 8000
     nodePort: 30001  # Changed to a valid port number
  selector:
    app: django
