version: '3.9'

services:
  mysql:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: olamidedevops
      MONGO_INITDB_ROOT_PASSWORD: TKgHFlQD4MtqpDYa

  django:
    image: authapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jwtAuth.settings
      - MONGO_DB_NAME=Authapp
      - MONGO_DB_USERNAME=olamidedevops
      - MONGO_DB_PASSWORD=TKgHFlQD4MtqpDYa
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb_data: