# version: '3.9'

# services:
#   mongodb:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: olamidedevops
#       MONGO_INITDB_ROOT_PASSWORD: TKgHFlQD4MtqpDYa

#   django:
#     image: authapp
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - DJANGO_SETTINGS_MODULE=jwtAuth.settings
#       - MONGO_DB_NAME=Authapp
#       - MONGO_DB_USERNAME=olamidedevops
#       - MONGO_DB_PASSWORD=TKgHFlQD4MtqpDYa
#       - MONGO_DB_HOST=mongodb
#       - MONGO_DB_PORT=27017
#     volumes:
#       - .:/app
#     depends_on:
#       - mongodb

# volumes:
#   mongodb_data:


# # services:
# #   django:
# #     image: authapp
# #     build: .
# #     ports:
# #       - "8000:8000"
# #     environment:
# #       - DJANGO_SETTINGS_MODULE=jwtAuth.settings
# #     volumes:
# #       - .:/app


version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: sqlite:3
    volumes:
      - ./db.sqlite3:/var/lib/sqlite3/db.sqlite3
