version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jwtAuth.settings
      - DATABASE_URL=mongodb+srv://olamidedevops:TKgHFlQD4MtqpDYa@auth.nleripr.mongodb.net/Authapp?retryWrites=true&w=majority&ssl=true
   

volumes:
  mongo_data:


