version: '3.9'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Devops@2024
      # MYSQL_PASSWORD: Devops@2024
      

  django:
    image: authapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jwtAuth.settings
      - MYSQL_DATABASE=authdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Devops@2024
      # - MYSQL_PASSWORD=Devops@2024
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
    volumes:
      - .:/app
    depends_on:
      - mysql

volumes:
  mysql_data: